# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# Setup
title:            Makigjuro's Tech Blog
tagline:          'Coding Tips and Tricks'
description:      ''
url:              https://makigjuro.github.io
baseurl:          /

author:
  name:           'Marjan Gjuroski'
  url:            https://www.linkedin.com/in/marjan-gjuroski-52295b24/

paginate:         5

# Custom vars
version:          2.1.0

github:           
  repo:           https://makigjuro.github.io

gem: [jekyll-paginate, jekyll-gists]
